### ISSUE TITLE
切换后台再切换回来的问题

### ISSUE THREAD

**Issue by sonygod** [sonygod/dengdeng_DEV#2]
进入了模型或漫游显示后，切换到
手机主页面，再按图标进入app，
希望能继续显示模型或漫游，避免
用户二次加载

**Comment by sonygod** [comment]
周5前看看

**Comment by sonygod** [comment]
fixed next version and will  public tomorrow.

**Comment by OneLiteCore** [comment]
已修正 2016-11-15_ver12
